#!/usr/bin/env bash
# One-time setup of the FaunaPulse release signing key.
#
# WHAT THIS IS: Android refuses to install an update unless the new file is signed
# with the SAME key as the version already on the phone. That key lives in a
# "keystore" file (.jks). This script creates it, then writes android/key.properties
# so Gradle can find it. Both stay out of git.
#
# LOSING THE KEYSTORE OR ITS PASSWORD IS PERMANENT: no one, including Google, can
# recover it, and every existing install would have to be uninstalled before users
# could move to a new key. Back it up (see the reminder printed at the end).
#
# Usage:
#   bash scripts/create_release_keystore.sh [/path/to/keystore.jks]
# Default keystore path: ~/faunapulse-release.jks (deliberately OUTSIDE the repo).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
KEYSTORE="${1:-$HOME/faunapulse-release.jks}"
ALIAS="faunapulse"
PROPS="$REPO_ROOT/android/key.properties"

command -v keytool > /dev/null || {
  echo "ERROR: keytool not found. It ships with the JDK (e.g. the one bundled with" >&2
  echo "Android Studio: <studio>/jbr/bin/keytool). Install a JDK and retry." >&2
  exit 1
}

if [ -e "$KEYSTORE" ]; then
  echo "ERROR: $KEYSTORE already exists. Refusing to overwrite it." >&2
  echo "That file IS your signing identity, replacing it would break app updates." >&2
  echo "If you meant to reuse it, only (re)create android/key.properties by hand," >&2
  echo "copying android/key.properties.example." >&2
  exit 1
fi

echo "Creating the FaunaPulse release keystore."
echo "  keystore : $KEYSTORE"
echo "  alias    : $ALIAS  (the name of the key inside the file)"
echo

# The certificate fields are cosmetic for a self-distributed app (nobody verifies
# them), but Play shows the organisation name, so use something recognisable.
read -r -p "Your name or organisation [FaunaPulse]: " CN
CN="${CN:-FaunaPulse}"
read -r -p "Two-letter country code [DE]: " COUNTRY
COUNTRY="${COUNTRY:-DE}"

echo
echo "Choose a password (at least 6 characters). It is NOT shown as you type."
echo "Store it in your password manager together with a copy of the keystore."
read -r -s -p "Password: " PW1
echo
read -r -s -p "Repeat password: " PW2
echo

[ "$PW1" = "$PW2" ] || { echo "ERROR: passwords do not match." >&2; exit 1; }
[ "${#PW1}" -ge 6 ] || { echo "ERROR: password must be at least 6 characters." >&2; exit 1; }

mkdir -p "$(dirname "$KEYSTORE")"

# -validity 10000 days (about 27 years): Google Play requires a key that stays
# valid well beyond 2033. PKCS12 is the modern keystore format and uses one
# password for both the store and the key.
keytool -genkeypair -v \
  -keystore "$KEYSTORE" \
  -storetype PKCS12 \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 2048 -validity 10000 \
  -dname "CN=$CN, C=$COUNTRY" \
  -storepass "$PW1" -keypass "$PW1"

chmod 600 "$KEYSTORE"

umask 077
cat > "$PROPS" << EOF
# Generated by scripts/create_release_keystore.sh — git-ignored, never commit.
storeFile=$KEYSTORE
storePassword=$PW1
keyAlias=$ALIAS
keyPassword=$PW1
EOF
chmod 600 "$PROPS"

echo
echo "Done."
echo "  keystore        : $KEYSTORE"
echo "  gradle settings : $PROPS  (git-ignored)"
echo
echo "Certificate fingerprint (identifies this key; Play shows the same value):"
# Older JDKs print "SHA-256:", newer ones "SHA256:", so accept both.
keytool -list -v -keystore "$KEYSTORE" -alias "$ALIAS" -storepass "$PW1" \
  | grep -iE "SHA-?256:" || true
echo
echo "BACK UP NOW, before building anything:"
echo "  1. Copy $KEYSTORE to at least two places you control"
echo "     (encrypted cloud folder, external drive, institutional storage)."
echo "  2. Save the password in your password manager, next to the file."
echo "  3. Never commit either one, and never put the password in an issue or email."
echo
echo "Next: flutter build apk --release --split-per-abi"
